defaults:
  - benchmark: split_cifar100.yaml
  - strategy: er.yaml
  - scheduler: null.yaml
  - evaluation: evaluation.yaml
  - optimizer: sgd.yaml
  - model: slimresnet18.yaml
  - experiment.yaml
  - hydra.yaml
  - deploy: default.yaml
