defaults:
  - benchmark: split_cifar100.yaml
  - strategy: der.yaml
  - evaluation: evaluation.yaml
  - scheduler: null.yaml
  - sgd_optimization.yaml
  - model.yaml
  - experiment.yaml
  - hydra.yaml
