defaults:
  - benchmark: split_cifar100.yaml
  - strategy: er.yaml
  - scheduler: null.yaml
  - evaluation: nologger.yaml
  - optimizer: sgd.yaml
  - model: slimresnet18.yaml
  - deploy: default.yaml
  - experiment.yaml
  - hydra.yaml

experiment:
  stop_at_experience: 4
