defaults:
  - benchmark: split_cifar100.yaml
  - scheduler: null.yaml
  - strategy: er_ace.yaml
  - evaluation: nologger.yaml
  - optimizer: sgd.yaml
  - model.yaml
  - experiment.yaml
  - hydra.yaml

experiment:
  stop_at_experience: 4
